function write_sysid_signal_header(filename,u)

fid = fopen(filename,'w');


fprintf(fid,'/*!\n');
fprintf(fid,'* \\file %s\n',filename);
fprintf(fid,'* \\brief System ID signal time history header\n');
fprintf(fid,'*\n');
fprintf(fid,'* \\details Autogenerated on %s\n',datestr(now));
fprintf(fid,'* \\ingroup systemid_fcns\n');
fprintf(fid,'*\n');
fprintf(fid,'* \\author University of Minnesota \n');
fprintf(fid,'* \\author Aerospace Engineering and Mechanics \n');
fprintf(fid,'* \\copyright Copyright 2011 Regents of the University of Minnesota. All rights reserved.\n');
fprintf(fid,'*\n');
fprintf(fid,'* $Id: write_sysid_signal_header.m 805 2012-04-24 14:11:28Z murch $\n');
fprintf(fid,'*/\n\n');

fprintf(fid,'#ifndef SYSID_LENGTH\n');
fprintf(fid,'   #define SYSID_LENGTH %d\n',length(u));
fprintf(fid,'#endif\n\n');

fprintf(fid,'static double %s[SYSID_LENGTH] = {\n',strrep(filename,'.h',''));

for i = 1:length(u)-1
    fprintf(fid,'%14.10f,',u(i));
    if ~mod(i,5)
        fprintf(fid,'\n');
    end
end

fprintf(fid,'%14.10f};\n',u(end));

fclose(fid);